micronaut:
  application:
    name: esop
netty:
  default:
    allocator:
      max-order: 3
jackson:
  mapper:
    allowCoercionOfScalars: false
app:
  max-wallet-limit: 10000000
  max-inventory-limit: 10000000
  platform-fee-percentage: 2